Badge:
  register_duration: 15
  recognize_duration: 3
  recognize_threshold: 0.4
  keep_threshold: 0.2
  keep_sp_threshold: 0.1
  recognize_sp_duration: 4
  recognize_sp_threshold: 0.3
  rms_threshold: 1000
  rms_peak_threshold: 5000
  gain: 10
  source: udp
  port_offset: 50000
  stream_kwargs:
    channels: 1
    rate: 16000
    format: int16
    chunk_size: 512
    buffer_duration: 5.0
    resample_method: audio_librosa
    host: 0.0.0.0

Jabra:
  register_duration: 15
  recognize_duration: 3
  recognize_threshold: 0.3
  keep_threshold: 0.1
  keep_sp_threshold: 0.1
  recognize_sp_duration: 4
  recognize_sp_threshold: 0.3
  rms_threshold: 1000   # jabra device rms threshold
  rms_peak_threshold: 5000   # jabra device rms peak threshold
  #  rms_threshold: 250 # macbook air internal mic rms threshold
  #  rms_peak_threshold: 250 # macbook air internal mic rms peak threshold
  gain: 0
  source: pyaudio
  stream_kwargs:
    channels: 1
    rate: 16000
    format: int16
    chunk_size: 512
    buffer_duration: 5.0
    resample_method: audio_librosa

Synchronizer:
  result_expiry_time: 5

PostAnalyzer:
  threshold: 0.2
  keep_threshold: 0.1
  segment_duration: 3

RTMP:
#  audio_streams: rtmp://uber-server.local/stream_01,rtmp://uber-server.local/stream_02,rtmp://uber-server.local/stream_03

InfluxDB:
#  url: http://ericli.local:8086
#  token: lrn6PxfmD_Sbde1Ke3LL5QOIc-QQJLT9Tw58-Y1pHXWfcsdljWMfwSOJ8F3CP3c20qYPiJ9UL8bSslELPW27lw== # ericli
  url: http://uber-server.local:8086
  token: eNMnz5EuJlWNukW15iI8ys734I7ZEgXKvQHi18AX4RtMWLQqBys6Rjfb5hfpmY_0YopaZUCEnhrMP7mx7e4d_A==
  org: admin

MQTT:
  host: uber-server.local
  port: 1883

Redis:
  host: uber-server.local
  port: 6379
  db: 0
  auth: mbox

Server:
  asr:
#    # nginx server on uber-server
#    audio_inference: http://uber-server.local:8080/infer
#    audio_resampling: http://uber-server.local:8080/resample
#    speech_enhancement: http://uber-server.local:8080/enhance
#    speech_separation: http://uber-server.local:8080/separate
#    speech_transcription: http://uber-server.local:8080/transcribe
#    voice_activity_detection: http://uber-server.local:8080/vad

    # nginx server on ericli
    audio_inference: http://ericli.local:8080/infer
    audio_resampling: http://ericli.local:8080/resample
    speech_enhancement: http://ericli.local:8080/enhance
    speech_separation: http://ericli.local:8080/separate
    speech_transcription: http://ericli.local:8080/transcribe
    voice_activity_detection: http://ericli.local:8080/vad

#    # local test on ericli
#    audio_inference: http://ericli.local:5000/infer
#    audio_resampling: http://ericli.local:5001/resample
#    speech_enhancement: http://ericli.local:5002/enhance
#    speech_separation: http://ericli.local:5003/separate
#    speech_transcription: http://ericli.local:5004/transcribe
#    voice_activity_detection: http://ericli.local:5005/vad

  vfa:
    frame_analyzer: http://uber-server.local:8080/frame_analyze


