# ASR-BASE config_template.yml
# Template for configuring audio, stream, database and server endpoints for the system

# base settings for badge devices (e.g., Nicla Vision)
Base_Badge:
  register_duration: 15             
  recognize_duration: 3             
  recognize_sp_duration: 4          
  recognize_threshold: 0.4          
  recognize_sp_threshold: 0.3       
  keep_threshold: 0.2               
  keep_sp_threshold: 0.1            
  rms_threshold: 500                
  rms_peak_threshold: 2500 
  update_threshold: 0.6
  gain: 10                          
  score_amplified: true             
  source: udp                       
  port_offset: 50000                
  stream_kwargs:                    
    channels: 1                     
    rate: 16000                     
    format: int16                   
    chunk_size: 512                 
    buffer_duration: 5.0            
    resample_method: audio_librosa  
    host: 0.0.0.0                   

# base settings for Jabra speaker
Base_Jabra:
  register_duration: 15
  recognize_duration: 3
  recognize_sp_duration: 4
  recognize_threshold: 0.3
  recognize_sp_threshold: 0.3
  keep_threshold: 0.1
  keep_sp_threshold: 0.1
  rms_threshold: 1000
  rms_peak_threshold: 5000
  update_threshold: 0.6
  gain: 0
  source: pyaudio
  stream_kwargs:
    channels: 1
    rate: 16000
    format: int16
    chunk_size: 512
    buffer_duration: 5.0
    resample_method: audio_librosa

# base settings for your device
Base_[Your_Device_Name]:
  register_duration:            # Seconds to record for registration
  recognize_duration:           # Seconds to record for recognition
  recognize_sp_duration:        # Seconds to record for recognition (with speech separation)
  recognize_threshold:          # Similarity threshold for recognition
  recognize_sp_threshold:       # Similarity threshold for recognition (with speech separation)
  keep_threshold:               # Similarity threshold for keeping identity for speaker border cases (with half-scaled recognition)
  keep_sp_threshold:            # Similarity threshold for keeping identity for speaker border cases (with half-scaled recognition and speech separation)
  rms_threshold:                # Root Mean Square amplitude value threshold for VAD preprocessing
  rms_peak_threshold:           # Peak amplitude value threshold for VAD preprocessing
  update_threshold:             # Similarity threshold for incrementally updating speaker profile
  gain:                         # Volume gain multiplier in decibels for audio preprocessing
  score_amplified:              # Whether to amplify the similarity score of the audio signal
  source:                       # AudioStream source type (udp/tcp/pyaudio/rtmp/lsl/file)
  file_dir:                     # Directory path containing audio files when source type is 'file', filename in format: <prefix>_<timestamp>.<extension>
  initial_sync_time:            # Unix timestamp to start synchronizing from when source type is 'file'
  port_offset:                  # Port offset for udp/tcp streams
  stream_kwargs:                # Additional stream settings
    channels:                   # Number of audio channels of the input device (if channels >1, channel selection is required)
    rate:                       # Sampling rate in Hz (e.g., 16000 for 16kHz)
    format:                     # Audio format, e.g., int16, float32
    chunk_size:                 # Size of each audio chunk in bytes (default to 512)
    buffer_duration:            # Buffer duration in seconds for audio stream
    resample_method:            # Resampling method for audio processing
    host:                       # listening address for udp/tcp streams (0.0.0 for all interfaces)
 
# synchronizer settings
Synchronizer:
  result_expiry_time: 10        # cleanup timeout (seconds)
  bucket_duration: 3            # time bucket duration (seconds) for synchronized result (default: recognize_duration)
  match_tolerance: 1.5          # matching tolerance (seconds) for incoming result to time buckets (default: ~bucket_duration/2)

# post analyzer settings
PostAnalyzer:
  threshold: 0.2                                  # Similarity threshold for recognition
  keep_threshold: 0.1                             # Special threshold for keeping identity for speaker border cases
  segment_duration: 3                             # Duration of each audio segment for analysis
  custom_origin_dir: path/to/origin/directory     # Default to <project_dir>/post-time/origin if null
  filenames: ['file_name.wav', 'file_name2.m4a']  # List of filenames in origin directory to process

# RTMP streams settings
RTMP:
  # Replace <example-rtmp-server> with your actual sever address that runs the RTMP server, and the <stream_id> with
  # the actual stream application in your RTMP server.
  # =================================================================================
  # e.g., if your RTMP server is on uber-server.local machine and its IP address is 192.168.1.12, and it has two streams
  # app named stream_01 and stream_02, then the following line should be:
  # audio_streams: ['rtmp://uber-server.local/stream_01', 'rtmp://192.168.1.12/stream_02']
  audio_streams: ['rtmp://<rtmp-example-server>/<stream_id>', ..]

# Database settings
InfluxDB:
  # Replace <inlfuxdb-example-server> with your actual sever address that runs the InfluxDB server, and the <port>
  # with the actual port number that InfluxDB server is listening to. The default port for InfluxDB is 8086.
  # Replace <influxdb-token> with your actual InfluxDB token, and <org-name> with your actual InfluxDB organization name.
  # =================================================================================
  # e.g., if your InfluxDB server is on uber-server.local machine and its IP address is 192.168.1.12 and listens on 8086,
  # and it has a token named lrn6PxfmD_Sbde1Ke3LL5QOIc-QQJLT9Tw58-Y1pHXWfcsdljWMfwSOJ8F3CP3c20qYPiJ9UL8bSslELPW27lw==
  # and organization named admin, then the following line should be:
  # url: http://uber-server.local:8086
  # token: lrn6PxfmD_Sbde1Ke3LL5QOIc-QQJLT9Tw58-Y1pHXWfcsdljWMfwSOJ8F3CP3c20qYPiJ9UL8bSslELPW27lw==
  # org: admin
  url: http://<influxdb-example-server>:<port>
  token: <influxdb-token>
  org: <org-name>

# MQTT settings
MQTT:
  # Replace <mqtt-example-server> with your actual sever address that runs the MQTT server, and the <port-number>
  # with the actual port number that MQTT server is listening to. The default port for MQTT is 1883.
  # =================================================================================
  # e.g., if your MQTT server is on uber-server.local machine and its IP address is 192.168.1.12, and it has listening
  # on port 1883, then the following line should be:
  # host: uber-server.local
  # port: 1883
  host: <mqtt-example-server>
  port: <port-number>

# Redis settings
Redis:
  # Replace <redis-example-server> with your actual sever address that runs the Redis server, and the <port-number>
  # with the actual port number that Redis server is listening to. Specify a certain database number you want to use for
  # message queue. The default database number is 0. The default port for Redis is 6379.
  # =================================================================================
  # e.g., if your Redis server is on uber-server.local machine and its IP address is 192.168.1.12, and it has listening
  # on port 6379, then the following line should be:
  # host: uber-server.local
  # port: 6379
  # db: 0
  host: <redis-example-server>
  port: <port-number>
  db: <database-number>

# Server settings
Server:
  # ASR server settings
  # Replace <asr-example-server> with your actual sever address that runs the ASR server or the load balancer
  # that proxy your ASR requests, and the <port> with the port numbers different ASR services listening on
  # or the port number that the load balancer listening on. The default port for ASR services is infer:5001,
  # resample:5002, enhance:5003, separate:5004, transcribe:5005, vad:5006. The default port for load balancer is 8080.
  # =================================================================================
  # e.g., if your ASR server is run on asr-server.local, and you have a load balancer on uber-server.local that proxy
  # your ASR requests, then the following line could be:
  # request ASR services from load balancer:
  # asr:
  #   audio_inferer: http://uber-server.local:8080/infer
  #   audio_resampler: http://uber-server.local:8080/resample
  #   speech_enhancer: http://uber-server.local:8080/enhance
  #   speech_separator: http://uber-server.local:8080/separate
  #   speech_transcriber: http://uber-server.local:8080/transcribe
  #   voice_activity_detector: http://uber-server.local:8080/vad
  #
  # or you can directly request the services from the ASR server:
  # asr:
  #   audio_inferer: http://asr-server.local:5001/infer
  #   audio_resampler: http://asr-server.local:5002/resample
  #   speech_enhancer: http://asr-server.local:5003/enhance
  #   speech_separator: http://asr-server.local:5004/separate
  #   speech_transcriber: http://asr-server.local:5005/transcribe
  #   voice_activity_detector: http://asr-server.local:5006/vad
  asr:
    audio_inferer: http://<asr-example-server>:<port>/infer
    audio_resampler: http://<asr-example-server>:<port>/resample
    speech_enhancer: http://<asr-example-server>:<port>/enhance
    speech_separator: http://<asr-example-server>:<port>/separate
    speech_transcriber: http://<asr-example-server>:<port>/transcribe
    voice_activity_detector: http://<asr-example-server>:<port>/vad