AprilTag:
  tag_size: 0.061
  families: tag36h11

VideoFrameAnalyzer:
  backend: openai
  top_p: 0
  temperature: 0
  ollama:
    api_key: ollama
    vlm_base_url: "http://localhost:11434/v1"
    llm_base_url: "http://localhost:11434/v1"
    vlm_model: "llava:13b"
    llm_model: llama3.1
    VLMExtraBody: {}
    LLMExtraBody: {}
  vllm:
    api_key: token-abc123
    vlm_base_url: "http://localhost:8000/v1"
    llm_base_url: "http://localhost:8001/v1"
    vlm_model: openbmb/MiniCPM-V-2_6
    llm_model: microsoft/Phi-3-small-128k-instruct
    VLMExtraBody:
      stop_token_ids: [151645, 151643]
    LLMExtraBody: {}
  openai:
    api_key: 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
    vlm_model: gpt-4o
    llm_model: gpt-4o
  defined_actions:
    Communicating: "when a person is directly facing another person and talking or explaining, with their hands away from keyboards, mice, screens, or hardware. Communication may involve gestures, pointing, or other non-verbal cues."
    Working-Software: "when a person is actively interacting with a device that has a screen, such as a laptop or tablet, typically using a keyboard, mouse, or touchscreen. This includes typing, coding, navigating interfaces, or running software, with no physical interaction with hardware components."
    Working-Hardware: "when a person is physically interacting with non-screen-based devices or components, such as breadboards, microcontrollers, LEDs, resistors, or wires. This includes assembling, adjusting, or troubleshooting hardware connections, with no active engagement with a screen or keyboard/mouse."
    Distracted: "when a person is disengaged from the experiment, focusing on unrelated activities such as using a mobile phone, looking away, or showing signs of inattention."
    Unclear: "when the activity cannot be confidently categorized into any of the above classes due to obscured views, ambiguous body language, or lack of sufficient context."
