upstreams:
  infer:
    - host: server-01.local
      port: 5001
      weight: 3
    - host: 192.168.3.2
      port: 5001
      weight: 3
    - host: server-03.local
      port: 5001
      weight: 1

  resample:
    - host: server-01.local
      port: 5002
      weight: 3
    - host: server-02.local
      port: 5002
      weight: 3
    - host: server-03.local
      port: 5002
      weight: 1

  enhance:
    - host: server-01.local
      port: 5003
      weight: 3
    - host: server-02.local
      port: 5003
      weight: 3
    - host: server-03.local
      port: 5003
      weight: 1

  separate:
    - host: server-01.local
      port: 5004
      weight: 3
    - host: server-02.local
      port: 5004
      weight: 3
    - host: server-03.local
      port: 5004
      weight: 1

  transcribe:
    - host: server-01.local
      port: 5005
      weight: 3
    - host: server-02.local
      port: 5005
      weight: 3
    - host: server-03.local
      port: 5005
      weight: 1

  vad:
    - host: server-01.local
      port: 5006
      weight: 3
    - host: server-02.local
      port: 5006
      weight: 3
    - host: server-03.local
      port: 5006
      weight: 1

rtmp_apps:
  - stream_01
  - stream_02
  - stream_03
  - stream_04
  - stream_05
