Badge:
  register_duration: 15
  recognize_duration: 3
  recognize_threshold: 0.4
  keep_threshold: 0.2
  keep_sp_threshold: 0.1
  recognize_sp_duration: 4
  recognize_sp_threshold: 0.3
  rms_threshold: 2500
  rms_peak_threshold: 15000
  listening_ip: 0.0.0.0
  port_offset: 50000
  protocol: UDP

Jabra:
  register_duration: 15
  recognize_duration: 3
  recognize_threshold: 0.3
  keep_threshold: 0.1
  keep_sp_threshold: 0.1
  recognize_sp_duration: 4
  recognize_sp_threshold: 0.3
  rms_threshold: 250
  rms_peak_threshold: 2500

Local:
  sr_model: titanet_large
  sp_model: damo/speech_mossformer2_separation_temporal_8k
  sp_model_local: /home/li/.cache/modelscope/hub/damo/speech_mossformer2_separation_temporal_8k
  tr_model: base.en
  language: en

PostAnalyzer:
  sr_model: titanet_large
  sp_model: damo/speech_mossformer2_separation_temporal_8k
  sp_model_local: /home/li/.cache/modelscope/hub/damo/speech_mossformer2_separation_temporal_8k
  tr_model: large-v3
  language: en
  threshold: 0.2
  keep_threshold: 0.1
  frame_rate: 16000
  channels: 1
  sample_width: 2
  segment_duration: 3

Synchronizer:
  result_expiry_time: 60

Recorder:
  format: paInt16
  record_rate: 16000
  chunk_size: 2000
  sample_width: 2
  channels: 1

InfluxDB:
  url: http://uber-server.local:8086
  token: nZO5yjoohyBGCyqGhChu98f2pgXEkou6wLXTax2nHvFjwsKnBtvHipT4uA_FX2QJUDY-R7uJBbTlFkpN312RKg==
  org: group_01

MQTT:
  mqtt_host: uber-server.local
  mqtt_port: 1883

Redis:
  redis_host: uber-server.local
  redis_port: 6379
  redis_db: 0
  redis_auth: mbox

Server:
  asr:
    audio_resampling: http://uber-server.local:8080/resample
    audio_inference: http://uber-server.local:8080/infer
    voice_activity_detection: http://uber-server.local:8080/vad
    speech_enhancement: http://uber-server.local:8080/enhance
    speech_separation: http://uber-server.local:8080/separate
    speech_transcription: http://uber-server.local:8080/transcribe
  vfa:
    frame_analyzer: http://uber-server.local:8080/frame_analyze


