active_experiments:
- experiment_id: exp_01
  title: pair programming
  status: active
  task_type: programming
- experiment_id: exp_02
  title: lego
  status: active
  task_type: lego_building
assignments:
  exp_01:
    alice:
      group_id: group_01
      tag_id: '1'
      description: brown hair and white shirt
    eric:
      group_id: group_01
      tag_id: '2'
      description: black hair, wear glasses, black sweater, male
  exp_02: {}
