- name: dell-01
  host: dell-01
  user: admin
  port: 22
  password: '12341234'
  key_path: ''
  remote_project_path: ~/OpenMMLA
- name: mac-01
  host: mac-01
  user: admin
  port: 22
  password: '12341234'
  key_path: ''
  remote_project_path: ~/OpenMMLA
- name: server-01
  host: server-01
  user: admin
  port: 22
  password: '12341234'
  key_path: ''
  remote_project_path: ~/OpenMMLA
- name: raspi4-03
  host: raspi4-03.local
  user: admin
  port: 22
  password: '12341234'
  key_path: ~/.ssh/id_ed25519.pub
  remote_project_path: ~/OpenMMLA
- name: raspi4-04
  host: raspi4-04.local
  user: admin
  port: 22
  password: '12341234'
  key_path: ~/.ssh/id_ed25519.pub
  remote_project_path: ~/OpenMMLA
- name: raspi5-02
  host: raspi5-02.local
  user: admin
  port: 22
  password: '12341234'
  key_path: ~/.ssh/id_ed25519.pub
  remote_project_path: ~/OpenMMLA
- name: raspi4-01
  host: raspi4-01.local
  user: admin
  port: 22
  password: '12341234'
  key_path: ~/.ssh/id_ed25519.pub
  remote_project_path: ~/OpenMMLA
- name: raspi5-01
  host: raspi5-01.local
  user: admin
  port: 22
  password: ''
  key_path: ~/.ssh/id_ed25519
  remote_project_path: ~/OpenMMLA
- name: raspi4-02
  host: raspi4-02.local
  user: admin
  port: 22
  password: ''
  key_path: ~/.ssh/id_ed25519
  remote_project_path: ~/OpenMMLA
