InfluxDB:
  url: http://ericli.local:8086
  token: ENC(gAAAAABqS3IbSaPLwTFjDDtPEcoTf0tHLaheWBFokY4T0bcPOY-Sx8l_FRdvTaW_bJiYlpuVx8BhvtnIe2vjBWgLsGtcxyqWCYBwqKlL9p23WpXhXoJmnQ-jFbwuP00lHPuQzU-3U0ENdaWvkr9GkLnrpPUxe9ngJDUAcvfPOAwb6Rf_nPxlRBKSTaJRczaF4qa0Pxf3-7pu)
  org: admin
  bucket: mmla-data
MongoDB:
  url: mongodb://ericli.local:27017
  db: openmmla
MQTT:
  host: ericli.local
  port: 1883
Redis:
  host: ericli.local
  port: 6379
  db: 1
Sudo:
  password: ENC(gAAAAABqjrHqKEILNNfVbGDzpSqY5ewe3m7lQqlxrml4kaH-OsLqVuLk6tHnh0z6C7DnmWvNFIj_SOc9RPe9Q-QEO3LBncLBEg==)
Gateway:
  host: ericli.local
  http_port: 8080
  rtmp_port: 1935
  scheme: http
