AudioEnhancer:

AudioInferer:
  model: titanet_large

AudioResampler:

SpeechSeparator:
  model: damo/speech_mossformer2_separation_temporal_8k
  model_local: /home/li/.cache/modelscope/hub/damo/speech_mossformer2_separation_temporal_8k

SpeechTranscriber:
  model: base.en
  language: en

VoiceActivityDetector:
