AudioEnhancer:
  cuda: true

AudioInferer:
  cuda: true
  onnx: false
  model: titanet_large

SpeechSeparator:
  cuda: true
  model: damo/speech_mossformer2_separation_temporal_8k
  model_local: .cache/modelscope/hub/damo/speech_mossformer2_separation_temporal_8k

SpeechTranscriber:
  cuda: true
  model: base.en
  language: en

VoiceActivityDetector:
  cuda: true
  onnx: true
